
server:
  port: 9099

zuul:
  ignored-patterns: /actuator/**
  routes:
    order-service:
      path: /api/v1/orders/**
      serviceId: order-service
      stripPrefix: false

#order-service:
#  ribbon:
#    NIWSServerListClassName: com.netflix.loadbalancer.ConfigurationBasedServerList
#    listOfServers: http://locahost:8201, http://locahost:8202


spring:
  application:
    name: api-gateway
#  cloud:
#    consul:
#      discovery:
#        enabled: false
#        id: ${spring.application.name}
#    config:
#      discovery:
#        enabled: false
#      enabled: false
#      host: localhost
#      port: 8500

logging:
  level:
    io:
      rks:
        apigateway:
          filters:
            zuul: debug

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
