server:
  port: 9090
  ssl:
    enabled: false
    key-alias: Ravendra Singh
    key-password: test123
    key-store: classpath:Ravendra_Singh.p12
    key-store-type: PKCS12
  error:
    include-binding-errors: always

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: user-management
        uri: lb://user-management
        predicates:
        - Path=/api/v1/auth/**
      - id: order-internal
        uri: lb://order-service
        predicates:
        - Path=/api/v1/orders/**
    discovery:
      enabled: true
    service-registry:
      auto-registration:
        enabled: true
#      - id: order-public
#        uri: lb://order-service
#        predicates:
#        - Path=/public/api/v1/order/**
#        filters:
#          - AuthenticationFilterFactory

  zipkin:
#    base-url: http://localhost:9411/
    enabled: false
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    enabled: true
    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com:
      rks:
        gateway: info


