spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:9411/

server:
  port: 9090
eureka:
  client:
    register-with-eureka: true

logging:
  level:
    org.springframework.cloud.gateway: info
    reactor.netty.http.client: info
