
#spring.cache.type=redis
#spring.redis.host=localhost
#spring.redis.port=6379

# AMQP RabbitMQ configuration
rabbitmq.enabled=false
# RabbitMQ Exchange and Queue Config, configure these if rabbitmq.enabled=true
#orderservice.exchange.name=orderservice-exchange
#orderservice.queue.name=orderservice-queue
#orderservie.routing.key=orderservice-routing-key

orderserviceconfig.localclientConfig.clientId=LOCALHOST
orderserviceconfig.localclientConfig.certificatePath=/Users/ravendrasingh/projects/data/certs
orderserviceconfig.localclientConfig.certFileName=Ravendra_Singh.cer
orderserviceconfig.localclientConfig.certificatePassword=test123


caching.enabled=false
debug=true