
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
#spring.test.database.replace=none
server.port=8210

mysql.username=root
mysql.password=4ec5fa62aafc42c3f15250ed97fd8fd3
mysql.url=jdbc:mysql://localhost:3306/orderservice-test?useSSL=false&allowPublicKeyRetrieval=true
mysql.driverName=com.mysql.jdbc.Driver


rabbitmq.enabled=false
caching.enabled=false
debug=true